name = "cf-trigger-gh"
main = "src/index.js"
compatibility_date = "2024-01-01"

# KV Namespace binding for deployment
# This will be created automatically by Cloudflare Deploy Button
[[kv_namespaces]]
binding = "CF_TRIGGER_KV"
id = "CF_TRIGGER_KV"

# Cron triggers - run every minute
[triggers]
crons = ["* * * * *"]

# Default environment variables
[vars]
WORKER_NAME = "CF Trigger Worker"
KV_NAMESPACE_NAME = "CF_TRIGGER_KV"
# Default values for demo - users should update these
GITHUB_REPO = "123hi123/tg-youbike"
WORKFLOW_ID = "176482748"
START_HOUR = "18"
END_HOUR = "23"
END_MINUTE = "30"
INTERVAL_MINUTES = "5"
TIMEZONE = "Asia/Taipei"

# Note: After deployment, add your GitHub PAT as a secret in Cloudflare Dashboard